import { useEffect, useState } from 'react';
import { api, getErrorMessage } from '../../services/api';

/** SRS UC-C6 / UC-C13 — weekly plans; publish auto-drafts */
export default function CoachPlans() {
  const [list, setList] = useState([]);
  const [player, setPlayer] = useState('');
  const [weekStart, setWeekStart] = useState('');
  const [title, setTitle] = useState('');
  const [goals, setGoals] = useState('');
  const [err, setErr] = useState('');

  const load = () =>
    api
      .get('/coaches/training-plans')
      .then((r) => setList(r.data.data || []))
      .catch((e) => setErr(getErrorMessage(e)));

  useEffect(() => {
    load();
  }, []);

  const create = async (e) => {
    e.preventDefault();
    try {
      await api.post('/coaches/training-plans', {
        player,
        weekStartDate: new Date(weekStart).toISOString(),
        title,
        goals,
        exercises: goals,
      });
      setTitle('');
      setGoals('');
      load();
    } catch (er) {
      alert(getErrorMessage(er));
    }
  };

  const publish = async (id) => {
    try {
      await api.put(`/coaches/training-plans/${id}`, { status: 'published', coachReviewed: true });
      load();
    } catch (er) {
      alert(getErrorMessage(er));
    }
  };

  return (
    <div className="space-y-8">
      <div>
        <h1 className="font-display text-5xl tracking-[0.08em] text-white">TRAINING ARSENALS</h1>
        <p className="font-headline text-xs uppercase tracking-[0.3em] text-slate-500">Weekly tactical plans</p>
        {err && <p className="text-sm text-red-400 mt-2">{err}</p>}
      </div>
      <form onSubmit={create} className="midnight-asymmetric max-w-xl space-y-3 border border-player-inner/40 bg-player-container p-5 shadow-player-card">
        <p className="font-display text-2xl tracking-[0.12em] text-white">FORGE NEW PLAN</p>
        <input
          className="w-full border-b-2 border-player-inner bg-player-bg px-3 py-2 text-sm text-white outline-none focus:border-[#ff7524]"
          placeholder="Player user ID"
          value={player}
          onChange={(e) => setPlayer(e.target.value)}
          required
        />
        <input
          type="date"
          className="w-full border-b-2 border-player-inner bg-player-bg px-3 py-2 text-sm text-white outline-none focus:border-[#ff7524]"
          value={weekStart}
          onChange={(e) => setWeekStart(e.target.value)}
          required
        />
        <input className="w-full border-b-2 border-player-inner bg-player-bg px-3 py-2 text-sm text-white outline-none focus:border-[#ff7524]" placeholder="Title" value={title} onChange={(e) => setTitle(e.target.value)} />
        <textarea className="w-full border-b-2 border-player-inner bg-player-bg px-3 py-2 text-sm text-white outline-none focus:border-[#ff7524]" placeholder="Goals / exercises" value={goals} onChange={(e) => setGoals(e.target.value)} />
        <button type="submit" className="w-full bg-[#ff7524] py-3 font-display text-xl tracking-[0.14em] text-black">
          GENERATE PLAN
        </button>
      </form>
      <ul className="grid gap-6 lg:grid-cols-2">
        {list.map((p) => (
          <li key={p._id} className="midnight-asymmetric border border-player-inner/40 bg-player-container p-5 text-sm shadow-player-card">
            <div className="mb-2 flex items-start justify-between">
              <span className="font-display text-3xl text-white">{p.title}</span>
              <span
                className={`rounded-full px-2 py-1 font-orbitron text-[10px] uppercase tracking-widest ${
                  p.status === 'draft' ? 'bg-amber-500/20 text-amber-200' : 'bg-player-green/10 text-player-green'
                }`}
              >
                {p.status}
                {p.isAutoGenerated ? ' · auto' : ''}
              </span>
            </div>
            <p className="font-headline text-xs uppercase tracking-[0.2em] text-slate-500">Player {p.player}</p>
            <pre className="mt-3 whitespace-pre-wrap text-xs text-slate-300">{p.goals || p.exercises}</pre>
            {p.status === 'draft' ? (
              <button type="button" className="mt-4 w-full bg-player-green/20 py-2 font-display text-sm text-player-green" onClick={() => publish(p._id)}>
                Publish to player (UC-C6)
              </button>
            ) : null}
          </li>
        ))}
      </ul>
    </div>
  );
}
